package com.rumshop.orders.config;

import com.rumshop.orders.model.Product;
import com.rumshop.orders.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {

    private final ProductRepository productRepository;

    @Override
    public void run(String... args) {
        if (productRepository.count() > 0) {
            return;
        }

        List<Product> products = List.of(
                createProduct("Wireless Noise-Cancelling Headphones",
                        "Premium over-ear headphones with active noise cancellation and 30-hour battery life",
                        new BigDecimal("299.99"), "wireless-noise-cancelling-headphones", "Electronics", 50, "ELEC-001",
                        "/images/products/wireless-noise-cancelling-headphones.svg"),
                createProduct("Ultra-Slim Laptop 15\"",
                        "Lightweight 15-inch laptop with 16GB RAM and 512GB SSD",
                        new BigDecimal("1299.99"), "ultra-slim-laptop-15", "Electronics", 25, "ELEC-002",
                        "/images/products/ultra-slim-laptop-15.svg"),
                createProduct("Smart Watch Pro",
                        "Advanced fitness tracking, heart rate monitoring, and 7-day battery life",
                        new BigDecimal("399.99"), "smart-watch-pro", "Electronics", 75, "ELEC-003",
                        "/images/products/smart-watch-pro.svg"),
                createProduct("4K Action Camera",
                        "Waterproof action camera with 4K video and image stabilization",
                        new BigDecimal("249.99"), "4k-action-camera", "Electronics", 40, "ELEC-004",
                        "/images/products/4k-action-camera.svg"),
                createProduct("Premium Cotton T-Shirt",
                        "100% organic cotton, comfortable fit, available in multiple colors",
                        new BigDecimal("39.99"), "premium-cotton-tshirt", "Clothing", 200, "CLTH-001",
                        "/images/products/premium-cotton-tshirt.svg"),
                createProduct("Leather Crossbody Bag",
                        "Handcrafted genuine leather bag with adjustable strap",
                        new BigDecimal("89.99"), "leather-crossbody-bag", "Clothing", 60, "CLTH-002",
                        "/images/products/leather-crossbody-bag.svg"),
                createProduct("Running Shoes Ultra",
                        "Lightweight running shoes with responsive cushioning",
                        new BigDecimal("129.99"), "running-shoes-ultra", "Clothing", 80, "CLTH-003",
                        "/images/products/running-shoes-ultra.svg"),
                createProduct("Denim Jacket Classic",
                        "Timeless denim jacket with a comfortable relaxed fit",
                        new BigDecimal("79.99"), "denim-jacket-classic", "Clothing", 45, "CLTH-004",
                        "/images/products/denim-jacket-classic.svg"),
                createProduct("Robot Vacuum Cleaner",
                        "Smart mapping, app control, and self-emptying base",
                        new BigDecimal("449.99"), "robot-vacuum-cleaner", "Home & Kitchen", 30, "HOME-001",
                        "/images/products/robot-vacuum-cleaner.svg"),
                createProduct("Stainless Steel Cookware Set",
                        "10-piece set with induction-compatible pots and pans",
                        new BigDecimal("199.99"), "stainless-steel-cookware-set", "Home & Kitchen", 35, "HOME-002",
                        "/images/products/stainless-steel-cookware-set.svg"),
                createProduct("Yoga Mat Premium",
                        "Extra thick non-slip mat with carrying strap",
                        new BigDecimal("49.99"), "yoga-mat-premium", "Sports", 100, "SPRT-001",
                        "/images/products/yoga-mat-premium.svg"),
                createProduct("Mountain Bike Helmet",
                        "Ventilated helmet with MIPS technology for enhanced safety",
                        new BigDecimal("69.99"), "mountain-bike-helmet", "Sports", 90, "SPRT-002",
                        "/images/products/mountain-bike-helmet.svg"),
                createProduct("Bluetooth Speaker Mini",
                        "Compact portable speaker with 12-hour battery and rich bass",
                        new BigDecimal("59.99"), "bluetooth-speaker-mini", "Electronics", 120, "ELEC-005",
                        "/images/products/bluetooth-speaker-mini.svg"),
                createProduct("Wireless Earbuds Pro",
                        "True wireless earbuds with active noise cancellation",
                        new BigDecimal("149.99"), "wireless-earbuds-pro", "Electronics", 85, "ELEC-006",
                        "/images/products/wireless-earbuds-pro.svg"),
                createProduct("Tablet 10\"",
                        "10-inch tablet with HD display and 64GB storage",
                        new BigDecimal("279.99"), "tablet-10", "Electronics", 55, "ELEC-007",
                        "/images/products/tablet-10.svg"),
                createProduct("Mechanical Keyboard RGB",
                        "Gaming mechanical keyboard with customizable RGB lighting",
                        new BigDecimal("119.99"), "mechanical-keyboard-rgb", "Electronics", 70, "ELEC-008",
                        "/images/products/mechanical-keyboard-rgb.svg"),
                createProduct("Wool Sweater Classic",
                        "Soft merino wool sweater, perfect for cool weather",
                        new BigDecimal("89.99"), "wool-sweater-classic", "Clothing", 65, "CLTH-005",
                        "/images/products/wool-sweater-classic.svg"),
                createProduct("Canvas Backpack",
                        "Sturdy canvas backpack with laptop compartment",
                        new BigDecimal("54.99"), "canvas-backpack", "Clothing", 95, "CLTH-006",
                        "/images/products/canvas-backpack.svg"),
                createProduct("Athletic Shorts",
                        "Moisture-wicking athletic shorts with built-in liner",
                        new BigDecimal("34.99"), "athletic-shorts", "Clothing", 150, "CLTH-007",
                        "/images/products/athletic-shorts.svg"),
                createProduct("Winter Parka",
                        "Insulated winter parka with hood and multiple pockets",
                        new BigDecimal("159.99"), "winter-parka", "Clothing", 40, "CLTH-008",
                        "/images/products/winter-parka.svg"),
                createProduct("Espresso Machine",
                        "Compact espresso maker with milk frother",
                        new BigDecimal("189.99"), "espresso-machine", "Home & Kitchen", 45, "HOME-003",
                        "/images/products/espresso-machine.svg"),
                createProduct("Air Fryer XL",
                        "Large capacity air fryer with digital controls",
                        new BigDecimal("129.99"), "air-fryer-xl", "Home & Kitchen", 60, "HOME-004",
                        "/images/products/air-fryer-xl.svg"),
                createProduct("Blender Pro",
                        "High-speed blender for smoothies and soups",
                        new BigDecimal("99.99"), "blender-pro", "Home & Kitchen", 75, "HOME-005",
                        "/images/products/blender-pro.svg"),
                createProduct("Coffee Grinder Burr",
                        "Electric burr grinder with 15 grind settings",
                        new BigDecimal("69.99"), "coffee-grinder-burr", "Home & Kitchen", 80, "HOME-006",
                        "/images/products/coffee-grinder-burr.svg"),
                createProduct("Kitchen Knife Set",
                        "8-piece chef knife set with wooden block",
                        new BigDecimal("149.99"), "kitchen-knife-set", "Home & Kitchen", 35, "HOME-007",
                        "/images/products/kitchen-knife-set.svg"),
                createProduct("Food Storage Containers",
                        "20-piece BPA-free food storage container set",
                        new BigDecimal("44.99"), "food-storage-containers", "Home & Kitchen", 110, "HOME-008",
                        "/images/products/food-storage-containers.svg"),
                createProduct("Resistance Bands Set",
                        "Set of 5 resistance bands with different tension levels",
                        new BigDecimal("24.99"), "resistance-bands-set", "Sports", 130, "SPRT-003",
                        "/images/products/resistance-bands-set.svg"),
                createProduct("Dumbbells Pair 10lb",
                        "Adjustable dumbbells with rubber coating",
                        new BigDecimal("79.99"), "dumbbells-pair-10lb", "Sports", 55, "SPRT-004",
                        "/images/products/dumbbells-pair-10lb.svg"),
                createProduct("Tennis Racket Pro",
                        "Professional tennis racket with carbon fiber frame",
                        new BigDecimal("119.99"), "tennis-racket-pro", "Sports", 45, "SPRT-005",
                        "/images/products/tennis-racket-pro.svg"),
                createProduct("Running Armband",
                        "Phone holder armband for running and workouts",
                        new BigDecimal("19.99"), "running-armband", "Sports", 180, "SPRT-006",
                        "/images/products/running-armband.svg"),
                createProduct("Foam Roller",
                        "High-density foam roller for muscle recovery",
                        new BigDecimal("34.99"), "foam-roller", "Sports", 95, "SPRT-007",
                        "/images/products/foam-roller.svg"),
                createProduct("Jump Rope Speed",
                        "Weighted speed jump rope for cardio training",
                        new BigDecimal("29.99"), "jump-rope-speed", "Sports", 120, "SPRT-008",
                        "/images/products/jump-rope-speed.svg"),
                createProduct("The Art of Programming",
                        "Comprehensive guide to clean code and software design",
                        new BigDecimal("24.99"), "the-art-of-programming", "Books", 85, "BOOK-001",
                        "/images/products/the-art-of-programming.svg"),
                createProduct("Cookbook Essentials",
                        "500 essential recipes for home cooks",
                        new BigDecimal("19.99"), "cookbook-essentials", "Books", 95, "BOOK-002",
                        "/images/products/cookbook-essentials.svg"),
                createProduct("Travel Photography Guide",
                        "Tips and techniques for stunning travel photos",
                        new BigDecimal("16.99"), "travel-photography-guide", "Books", 70, "BOOK-003",
                        "/images/products/travel-photography-guide.svg"),
                createProduct("Self-Help Best Seller",
                        "Bestselling guide to personal growth and productivity",
                        new BigDecimal("14.99"), "self-help-best-seller", "Books", 150, "BOOK-004",
                        "/images/products/self-help-best-seller.svg"),
                createProduct("Mystery Novel Collection",
                        "Thrilling mystery series box set",
                        new BigDecimal("29.99"), "mystery-novel-collection", "Books", 45, "BOOK-005",
                        "/images/products/mystery-novel-collection.svg"),
                createProduct("Children's Storybook",
                        "Illustrated storybook for ages 4-8",
                        new BigDecimal("12.99"), "childrens-storybook", "Books", 200, "BOOK-006",
                        "/images/products/childrens-storybook.svg"),
                createProduct("Vitamin C Serum",
                        "Anti-aging serum with 20% vitamin C",
                        new BigDecimal("34.99"), "vitamin-c-serum", "Beauty", 90, "BEAU-001",
                        "/images/products/vitamin-c-serum.svg"),
                createProduct("Hydrating Face Cream",
                        "Deep moisturizing cream for all skin types",
                        new BigDecimal("28.99"), "hydrating-face-cream", "Beauty", 110, "BEAU-002",
                        "/images/products/hydrating-face-cream.svg"),
                createProduct("Lipstick Set",
                        "Set of 6 long-lasting lipstick shades",
                        new BigDecimal("24.99"), "lipstick-set", "Beauty", 75, "BEAU-003",
                        "/images/products/lipstick-set.svg"),
                createProduct("Hair Dryer Professional",
                        "Salon-quality hair dryer with ionic technology",
                        new BigDecimal("79.99"), "hair-dryer-professional", "Beauty", 50, "BEAU-004",
                        "/images/products/hair-dryer-professional.svg"),
                createProduct("Essential Oil Diffuser",
                        "Ultrasonic aromatherapy diffuser with LED lights",
                        new BigDecimal("39.99"), "essential-oil-diffuser", "Beauty", 85, "BEAU-005",
                        "/images/products/essential-oil-diffuser.svg"),
                createProduct("Nail Polish Collection",
                        "Set of 10 long-wear nail polish colors",
                        new BigDecimal("18.99"), "nail-polish-collection", "Beauty", 120, "BEAU-006",
                        "/images/products/nail-polish-collection.svg"),
                createProduct("Board Game Strategy",
                        "Award-winning family strategy board game",
                        new BigDecimal("34.99"), "board-game-strategy", "Toys & Games", 65, "TOYS-001",
                        "/images/products/board-game-strategy.svg"),
                createProduct("Building Blocks Set",
                        "500-piece construction building blocks set",
                        new BigDecimal("49.99"), "building-blocks-set", "Toys & Games", 55, "TOYS-002",
                        "/images/products/building-blocks-set.svg"),
                createProduct("Puzzle 1000 Pieces",
                        "Landscape jigsaw puzzle, 1000 pieces",
                        new BigDecimal("19.99"), "puzzle-1000-pieces", "Toys & Games", 80, "TOYS-003",
                        "/images/products/puzzle-1000-pieces.svg"),
                createProduct("Remote Control Car",
                        "1:18 scale RC car with 2.4GHz control",
                        new BigDecimal("59.99"), "remote-control-car", "Toys & Games", 45, "TOYS-004",
                        "/images/products/remote-control-car.svg"),
                createProduct("Card Game Party",
                        "Fast-paced party card game for 4-12 players",
                        new BigDecimal("14.99"), "card-game-party", "Toys & Games", 140, "TOYS-005",
                        "/images/products/card-game-party.svg"),
                createProduct("Plush Toy Bear",
                        "Soft plush teddy bear, 12 inches",
                        new BigDecimal("24.99"), "plush-toy-bear", "Toys & Games", 95, "TOYS-006",
                        "/images/products/plush-toy-bear.svg"),
                createProduct("Albertxidil Hair Growth Serum",
                        "Revolutionary hair and beard growth formula. Grow a magnificent mane and a legendary beard in weeks. Clinically tested, Albert-approved.",
                        new BigDecimal("49.99"), "albertxidil", "Beauty", 200, "BEAU-007",
                        "/images/products/albertxidil.svg"),
                createProduct("Enzodol Max Force Pain Relief",
                        "The legendary ointment by Enzo. One rub and pain runs away screaming. Formulated with volcanic thermal extract, capsaicin turbo blend, and Enzo's secret ingredient. Apply generously and feel the burn before the relief.",
                        new BigDecimal("34.99"), "enzodol-max-force", "Beauty", 300, "BEAU-008",
                        "/images/products/enzodol.svg")
        );

        productRepository.saveAll(products);
    }

    private Product createProduct(String name, String description, BigDecimal price,
                                 String slug, String category, int stock, String sku, String imageUrl) {
        return Product.builder()
                .name(name)
                .description(description)
                .price(price)
                .imageUrl(imageUrl)
                .category(category)
                .stockQuantity(stock)
                .sku(sku)
                .slug(slug)
                .build();
    }
}
